# Generated by Django 3.2 on 2021-05-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.CharField(max_length=30)),
                ('productname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('unitprice', models.IntegerField()),
                ('currentstock', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
