# Generated by Django 3.2 on 2021-05-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=200)),
                ('customerphone', models.CharField(max_length=20)),
                ('customeremail', models.EmailField(max_length=254)),
                ('totalordersum', models.IntegerField()),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
